### ISSUE TITLE
Players losing items when out of box

### ISSUE THREAD

**Issue by forward1232** [MrDarkiMCReal/PvPZones#1]
when player is out from the area items that player carried was cleared. 
сould you please add saving items before player jumps into the box and give them back when player is out of area

**Comment by MrDarkiMCReal** [comment]
Greetings.
Its already done and will be avaliable in version 1.3
code of v1.3 is on code-page so if you want you can download and build it yourself
or just wait few days untill i test everything and drop final built to spigotmc page
